Started Issue Tracker Home file with a table
tupes/comit-saskatoon-react pull request #51
Opened 2020-10-06 00:45 UTC by gravinblumenn

2020-10-06 07:07 UTC, tupes commented on applications/issue-tracker/Home.html
> +                <header><h1><a href="Home.html">Issue Tracker</a></h1></header>
`<ul>` elements can only contain `<li>` elements

2020-10-06 07:12 UTC, tupes requested changes, later dismissed
Good job! 

Just one thing to fix. Also, you should change the name of the file to `home.html` to follow naming conventions. Optional: you could put the date values inside of `<date>` elements.

2020-10-07 01:32 UTC, JoshMacSween approved these changes
Looks good to me, Gavin! 👍

2020-10-07 01:33 UTC, JoshMacSween approved these changes

2020-10-07 03:07 UTC, merged